robot:
  - name: link_0
    order: 0
    translate: [0.0, 0.0, 0.0]
    rotate: [0, 0, 0]
    angleAxis: [0, 0, 1]
    translateLink: [0.0, 0.0, 0.0]
    rotateLink: [0, 0, 3.1415926]
    mesh: base_link.STL

  - name: link_1
    order: 1
    translate: [0.0, 0.0, 0.348]
    rotate: [0, 0, 0.0]
    angleAxis: [0, 0, 1]
    translateLink: [0.0, 0.0, 0.0]
    rotateLink: [0, 0, 0]
    mesh: arm1.STL

  - name: link_2
    order: 2
    translate: [0.0, 0.0, 0]
    rotate: [1.5707963267948966, 0, 0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: arm2.STL

  - name: link_3
    order: 3
    translate: [0.0, 0.410, 0.0]
    rotate: [-1.5707963267948966, 0.0, 0.0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: arm3.STL

  - name: link_4
    order: 4
    translate: [0.0, 0.0, 0.0]
    rotate: [1.5707963267948966, 0, 0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh:  arm4.STL

  - name: link_5
    order: 5
    translate: [0.0, 0.401, 0.0]
    rotate: [-1.5707963267948966, 0, 0.0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0]
    rotateLink: [ 0, 0, 0 ]
    mesh: arm5.STL

  - name: link_6
    order: 6
    translate: [0.0, 0.0, 0.0]
    rotate: [1.5707963267948966, 0, 0]
    angleAxis: [0, 0, 1]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: arm6.STL

  - name: link_7
    order: 7
    translate: [ 0.0, 0.230, 0.0 ]
    rotate: [-1.5707963267948966, 0, 0]
    angleAxis: [ 0, 0, 1 ]
    translateLink: [ 0.0, 0.0, 0.0 ]
    rotateLink: [ 0, 0, 0 ]
    mesh: arm7.STL